apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - manager.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: flux-iac/tofu-controller
    newName: ghcr.io/liatrio/tofu-controller
    newTag: v0.0.3
