apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rhoofard/terraform-modules
  ref:
    branch: main