apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: test
  namespace: flux-system
spec:
  path: ./null/
  interval: 10m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: test
  runnerPodTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: tf-runner
        app.kubernetes.io/created-by: tf-controller

