name: helm-release
on:
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      packages: write # needed for ghcr access
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Publish Helm chart in GitHub Pages
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Helm OCI
        run: |
          VERSION=$(yq e '.version' charts/tofu-controller/Chart.yaml)
          mkdir helm-release
          helm package charts/tofu-controller/ -d helm-release
          helm push helm-release/tofu-controller-${VERSION}.tgz oci://ghcr.io/liatrio/charts
